Core: fix ChildTopicsModel for multi-value (#985).
The `ChildTopicsModel`'s `put()` method that takes a `List` parameter (for multi-value childs) doesn't throw this exception anymore:
{{{
java.lang.IllegalArgumentException: Tried to build a SimpleValue from a java.util.ArrayList (expected are String, Integer, Long, Double, or Boolean)
}}}

As a consequence the `Facets` API's `getFacettedTopic()` method works properly.

Thanks to Malte for reporting!

BREAKING CHANGE

Core API:

1 method changed in `DeepaMehtaUtils`:
{{{
public static List<TopicModel> toTopicModels(Iterable<? extends Topic> topics)
-->
public static      <M> List<M> toModelList(Iterable<? extends DeepaMehtaObject> objects)
}}}

It can now map any DM object collection to the corresponding model objects.
Note the method renaming.

See #985.