Webclient: fix again view config defaults (#208).
This (client-side) error does not accur anymore:
{{{
    TextRendererError: field "xx" has no "input_field_rows" setting
}}}

If no "Input Field Rows" value is set (or if it is 0) then 1 is used as the default.

Was fixed already but broke 3 days ago.

See ticket 208.