Downgrade from Lucene 3.0.1 to 3.0.0
Tried to fix that error:

org.osgi.framework.BundleException: Constraint violation for package 'org.apache.lucene' when resolving module 11.0 between existing export 11.0.org.apache.lucene NO BLAME and uses constraint 13.0.org.apache.lucene BLAMED ON [[11.0] package; (&(package=org.apache.lucene.util)(version>=3.0.0))]

Doesn't work.

Bundle list:
11|Installed  |    5|Neo4j - Lucene Index (0.2.0.2)
13|Active     |    5|Apache ServiceMix :: Bundles :: lucene-core (3.0.0.1)

For Neo4j - Lucene Index the Felix web console lists:
Imported Packages: org.apache.lucene.util,version=3.0 from org.apache.servicemix.bundles.lucene (13)
Exported Packages: org.apache.lucene                    <== Possibly this version-less export ...

For lucene-core the Felix web console lists:
Exported Packages: org.apache.lucene,version=3.0.0      <== ... contradicts with this one
                   org.apache.lucene.util,version=3.0.0

Note: in contrast to current master and improve-build-process branches we use the new index framework of Neo4j 1.2, that's
    <artifactId>neo4j-lucene-index</artifactId>
    <version>0.2-1.2</version>
instead of
    <artifactId>neo4j-index</artifactId>
    <version>1.2-1.2</version>

Furthermore: DB is shutdown properly when creating the Lucene index fails. No endless retries to start the DM core bunlde.