Webservice: errors are mapped as well (#484).
The JAX-RS Exception Mapper maps errors as well (not just RuntimeExceptions).
Thus the exception log is still readable when e.g. a NoClassDefFoundError occurred.

The provider class is renamed:
{{{
RuntimeExceptionMapper -> CatchAllExceptionMapper
}}}

Close #484.