Deploy Neo4j MehtaGraph 1.1-SNAPSHOT (#302).
The parent POM is updated to version 4 in order to deploy a fixed Neo4j MehtaGraph.

This error doesn't appear anymore when searching:
{{{
java.lang.RuntimeException: Searching topics failed (searchTerm="komplexe", fieldUri="null", clientState={dm4_topicmap_id=10631, JSESSIONID=17vsf61a7y90guti3xxblerxc, dm4_workspace_id=9676})
	at de.deepamehta.core.impl.service.EmbeddedService.searchTopics(EmbeddedService.java:145)
	at de.deepamehta.plugins.webclient.WebclientPlugin.searchTopics(WebclientPlugin.java:79)
	... 47 more
Caused by: java.lang.IllegalArgumentException: Reference error: ID 76173 refers to a MehtaEdge when the caller expects a MehtaNode
    at de.deepamehta.mehtagraph.impl.Neo4jBase.buildMehtaNode(Neo4jBase.java:71)
    at de.deepamehta.mehtagraph.impl.Neo4jMehtaGraph.queryMehtaNodes(Neo4jMehtaGraph.java:113)
    at de.deepamehta.core.impl.storage.MGStorageBridge.searchTopics(MGStorageBridge.java:143)
    at de.deepamehta.core.impl.service.EmbeddedService.searchTopics(EmbeddedService.java:140)
}}}

At client-side this error appears as
{{{
ERROR while searching:

"RESTClientError: GET request failed (error: Internal Server Error)"
}}}

As a workaround MehtaEdge results are just dropped.
The underlying problem remains to be investigated.

See ticket 302.