More telling log in case of updated plugin (#693).
When an error occurs while event handling, in particular an error caused by an outdated plugin (not yet adapted to Core API changes) like `NoSuchMethodError` or `AbstractMethodError` the log is more informative in that case.

Close #693.