Core: meta type can be child in assoc def (#363).
So, you can define e.g. an aggregation definition with "Topic Type" as its child type.
This is required e.g. by the external dm4-mail plugin.

This error doesn't occur anymore:
    java.lang.RuntimeException: DB inconsistency: type "dm4.mail.config.type"
    has 4 association definitions but in sequence are 5

See ticket 363.